name: linux-clipboard
base: core24
version: '1.1.1'
icon: src-tauri/icons/icon.png
summary: A modern clipboard manager for Linux Mint
description: |
  A modern, efficient, and visual clipboard manager for Linux Mint and other distributions.
  Features text and image history, categorization, drag-and-drop, and system tray integration.

grade: stable
confinement: strict
license: MIT
website: https://github.com/Bruno33223/Linux-Clipboard
source-code: https://github.com/Bruno33223/Linux-Clipboard
issues: https://github.com/Bruno33223/Linux-Clipboard/issues

apps:
  linux-clipboard:
    command: bin/linux-clipboard
    extensions: [gnome]
    desktop: usr/share/applications/linux-clipboard.desktop
    plugs:
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - gsettings
      - network
      - opengl
      - audio-playback
      - mount-observe
      - system-observe

parts:
  linux-clipboard:
    plugin: nil
    source: src-tauri/target/release
    override-build: |

      mkdir -p $CRAFT_PART_INSTALL/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons/hicolor/512x512/apps

      if [ -f "$CRAFT_PART_SRC/app" ]; then
        cp "$CRAFT_PART_SRC/app" "$CRAFT_PART_INSTALL/bin/linux-clipboard"
      else
        echo "Binary not found"
        exit 1
      fi

      # ---------------------------------------------------------
      # CORREÇÃO DA CÓPIA DO ÍCONE E DESKTOP (Usando find para segurança)
      # ---------------------------------------------------------
      
      # Encontra o ícone png (ignora maiúsculas/minúsculas no nome)
      ICON_SRC=$(find "$CRAFT_PART_SRC/bundle/appimage" -iname "*.png" | head -n 1)
      if [ -n "$ICON_SRC" ]; then
        cp "$ICON_SRC" "$CRAFT_PART_INSTALL/usr/share/icons/hicolor/512x512/apps/linux-clipboard.png"
      else
        echo "ERRO: Ícone .png não encontrado no bundle AppImage!"
        exit 1
      fi

      # Encontra o arquivo .desktop
      DESKTOP_SRC=$(find "$CRAFT_PART_SRC/bundle/appimage" -name "*.desktop" | head -n 1)
      if [ -n "$DESKTOP_SRC" ]; then
        cp "$DESKTOP_SRC" "$CRAFT_PART_INSTALL/usr/share/applications/linux-clipboard.desktop"
        
        # Força o Exec e o Icon corretos
        sed -i 's/^Exec=.*/Exec=linux-clipboard/' "$CRAFT_PART_INSTALL/usr/share/applications/linux-clipboard.desktop"
        sed -i 's/^Icon=.*/Icon=linux-clipboard/' "$CRAFT_PART_INSTALL/usr/share/applications/linux-clipboard.desktop"
      else
         echo "ERRO: Arquivo .desktop não encontrado!"
         exit 1
      fi
    stage-packages:
      - libgtk-3-0
      - libgdk-pixbuf-2.0-0
      - libglib2.0-0
      - libcairo2
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libx11-6
      - libwayland-client0
      - libxkbcommon0
      - libgl1
      - libegl1
      - libicu74
      - libwebkit2gtk-4.1-0
      - libjavascriptcoregtk-4.1-0
      - libsoup-3.0-0
      - libsecret-1-0
      - libjpeg-turbo8
      - libpng16-16
      - libwebp7
