name: linux-clipboard
base: core24
version: '1.1.1'
icon: src-tauri/icons/icon.png
summary: A modern clipboard manager for Linux Mint
description: |
  A modern, efficient, and visual clipboard manager for Linux Mint and other distributions.
  Features text and image history, categorization, drag-and-drop, and system tray integration.

grade: stable
confinement: strict
license: MIT
website: https://github.com/Bruno33223/Linux-Clipboard
source-code: https://github.com/Bruno33223/Linux-Clipboard
issues: https://github.com/Bruno33223/Linux-Clipboard/issues

layout:
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1

apps:
  linux-clipboard:
    command: bin/linux-clipboard
    extensions: [gnome]
    desktop: usr/share/applications/linux-clipboard.desktop
    environment:
      WEBKIT_FORCE_SANDBOX: "0"
      WEBKIT_DISABLE_DMABUF_RENDERER: "1"
      WEBKIT_DISABLE_COMPOSITING_MODE: "1"
      WEBKIT_EXEC_PATH: "$SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1"
      XDG_DATA_DIRS: "$SNAP/usr/share:$XDG_DATA_DIRS"
    plugs:
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - gsettings
      - network
      - opengl
      - audio-playback
      - mount-observe
      - system-observe

parts:
  linux-clipboard:
    plugin: nil
    source: src-tauri/target/release
    override-build: |

      mkdir -p $CRAFT_PART_INSTALL/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons/hicolor/512x512/apps

      if [ -f "$CRAFT_PART_SRC/app" ]; then
        cp "$CRAFT_PART_SRC/app" "$CRAFT_PART_INSTALL/bin/linux-clipboard"
      else
        echo "Binary not found"
        exit 1
      fi

      # ---------------------------------------------------------
      # CORREÇÃO DA CÓPIA DO ÍCONE E DESKTOP
      # ---------------------------------------------------------
      
      # Procura o ícone (prioriza o do bundle, senão usa o do src-tauri)
      if [ -f "$CRAFT_PART_SRC/bundle/appimage/usr/share/icons/hicolor/512x512/apps/linux-clipboard.png" ]; then
        cp "$CRAFT_PART_SRC/bundle/appimage/usr/share/icons/hicolor/512x512/apps/linux-clipboard.png" "$CRAFT_PART_INSTALL/usr/share/icons/hicolor/512x512/apps/linux-clipboard.png"
      elif [ -f "$CRAFT_PROJECT_DIR/src-tauri/icons/icon.png" ]; then
         cp "$CRAFT_PROJECT_DIR/src-tauri/icons/icon.png" "$CRAFT_PART_INSTALL/usr/share/icons/hicolor/512x512/apps/linux-clipboard.png"
      else
        echo "ERRO: Ícone não encontrado!"
        exit 1
      fi

      # Encontra o arquivo .desktop
      DESKTOP_SRC=$(find "$CRAFT_PART_SRC/bundle/appimage" -name "*.desktop" | head -n 1)
      if [ -n "$DESKTOP_SRC" ]; then
        cp "$DESKTOP_SRC" "$CRAFT_PART_INSTALL/usr/share/applications/linux-clipboard.desktop"
        
        # Ajusta Exec e Icon para o ambiente Snap
        sed -i 's/^Exec=.*/Exec=linux-clipboard/' "$CRAFT_PART_INSTALL/usr/share/applications/linux-clipboard.desktop"
        sed -i 's/^Icon=.*/Icon=linux-clipboard/' "$CRAFT_PART_INSTALL/usr/share/applications/linux-clipboard.desktop"
      else
         echo "ERRO: Arquivo .desktop não encontrado no bundle!"
         # Fallback: cria um .desktop básico se não existir
         cat <<EOF > "$CRAFT_PART_INSTALL/usr/share/applications/linux-clipboard.desktop"
      [Desktop Entry]
      Name=Linux Clipboard
      Comment=A modern clipboard manager for Linux Mint
      Exec=linux-clipboard
      Icon=linux-clipboard
      Type=Application
      Categories=Utility;
      EOF
      fi
    stage-packages:
      - libgtk-3-0
      - libgdk-pixbuf-2.0-0
      - libglib2.0-0
      - libcairo2
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libx11-6
      - libwayland-client0
      - libxkbcommon0
      - libgl1
      - libegl1
      - libicu74
      - libwebkit2gtk-4.1-0
      - libjavascriptcoregtk-4.1-0
      - libsoup-3.0-0
      - libsecret-1-0
      - libjpeg-turbo8
      - libpng16-16
      - libwebp7
      - libappindicator3-1
      - gir1.2-appindicator3-0.1
      - librsvg2-common
      - glib-networking
      - gsettings-desktop-schemas
      - libcanberra-gtk-module
      - libcanberra-gtk3-module
